server:
  port: 9001

spring:
  application:
    name: moonson-business-user
  cache:
    type: redis
    redis:
      cache-null-values: true
      # 以时间单位结尾：H、M、S
      time-to-live: 600S
      key-prefix: "spring:cache:"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8   #或UT
  session:
    store-type: REDIS
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    moonson:
      # 使用阿里的Druid连接池
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.35.88.207:3306/moonson?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      druid:
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 3
        min-idle: 9
        maxActive: 66
        # 配置获取连接等待超时的时间
        maxWait: 5000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 1000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
    nacos:
#      config:
#        server-addr: 101.35.88.207:8848
#        username: nacos
#        password: nacos
      discovery:
        server-addr: 101.35.88.207:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8080
#      datasource:
#        flow-ds:
#          nacos:
#            server-addr: 101.35.88.207:8848
#            data-id: article-service-flow-rules
#            group-id: DEFAULT_GROUP
#            rule-type: flow
#            username: nacos
#            password: nacos


logging:
  level:
    root: info
    com.jf.moonson: debug

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
    # 请求与响应的压缩以提高通信效率
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json,image/jpeg
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 10000
        logger-level: full # 完整信息

## elasticsearch
es:
  username: elastic
  password: 8RWTLqfPPrjXnTWoplWylldOS_K9u
  hosts:
    - 101.35.88.207:9200


management:
  endpoints:
    web:
      exposure:
        include: '*' # 默认对外暴露所有健康检查项